application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  # Value retrieved from Postmark's API documentation
  base_url: "localhost"
  # Use the single sender email you authorised on Postmark!
  sender_email: "test@gmail.com"
